name: dbtvault_snowflake_demo
profile: snowflake_demo
version: '5.2.0'
config-version: 2


snapshot-paths: 
  - snapshots
analysis-paths:
  - analysis
clean-targets:
  - target
data-paths:
  - data
macro-paths:
  - macros
source-paths:
  - models
test-paths:
  - tests
  - DQ_Test
target-path: target

vars:
  load_date: '1992-01-09'
  tpch_size: 10 #1, 10, 100, 1000, 10000
  batch_id: '{{ invocation_id }}' #This is going to be overwritten from ADF in actual run, but let's keep as invocation id as default value, makes easier life when debugging dbt
  job_id: 'Null'
  batch_status : ''
  job_status : ''


models:
  dbtvault_snowflake_demo:
    LennarHomeSite:
      tags:
        - 'hs'
      materialized: table
      +schema:  "{{env_var('DBT_TGT_SCHEMA') }}"
    raw_stage:
      tags:
        - 'raw'
      materialized: view
      +schema: "{{env_var('DBT_TGT_SCHEMA') }}"
    stage:
      tags:
        - 'stage'
      enabled: true
      materialized: view
      +schema: "{{env_var('DBT_TGT_SCHEMA') }}"
    raw_vault:
      tags:
        - 'raw_vault'
      materialized: incremental
      +schema: "{{env_var('DBT_TGT_SCHEMA') }}"
      hubs:
        tags:
          - 'hub'
      links:
        tags:
          - 'link'
      sats:
        tags:
          - 'satellite'
      t_links:
        tags:
          - 't_link'

  
    



