name: dbtvault_snowflake_demo
profile: snowflake_demo
version: '5.2.0'
config-version: 2



macro-paths:
  - macros
source-paths:
  - models


vars:
  load_date: '1992-01-09'
  tpch_size: 10 #1, 10, 100, 1000, 10000
  batch_id: '{{ invocation_id }}' #This is going to be overwritten from ADF in actual run, but let's keep as invocation id as default value, makes easier life when debugging dbt
  job_id: 'Null'
  batch_status : ''
  job_status : ''


models:

    raw_stage:
      tags:
        - 'raw'
      materialized: view
      +schema: 'DBT_ABASAK_CUST_DETAIL'
      raw_inventory:
        materialized: view
        +schema: 'DBT_ABASAK_CUST_DETAIL'
      raw_order:
        materialized: view
        +schema: 'DBT_ABASAK_CUST_DETAIL'
    LennarHomeSite:
      tags:
        - 'raw'
      materialized: view
      +schema: 'dbt_abasak'
      SAT_HomeSite:
        materialized: view
        +schema: 'dbt_abasak'
    test_suit:
      tags:
        - 'raw'
      materialized: view
      +schema: 'dbt_abasak'
      sat_homsite_tests:
        materialized: view
        +schema: 'dbt_abasak'

  
    


