version: 2

sources:
  - name: tpch_sample
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF{{ var('tpch_size', 10) }}
    tables:
      - name: LINEITEM
      - name: CUSTOMER
      - name: ORDERS
      - name: PARTSUPP
      - name: SUPPLIER
      - name: PART
      - name: NATION
      - name: REGION
  - name: Homesite
    database: PC_DBT_DB
    schema: DBT_ABASAK
    tables:
      - name: HOMESITEMASTER



models:
  - name: SAT_HomeSite
    columns:
        - name: HOMESITEID
          tests:
            - unique:
                config:            
                  severity: warn
        - name: ADDRESSLINE1
          tests:
            - not_null:
                config:            
                  severity: warn
        - name: HOMESTATUS
          tests:
            - accepted_values:
                values: ['S', 'H', 'M', 'C','Z']
                config:            
                  severity: warn
        - name: PLANCODE
          tests:
            - str_len_check:
                desired_len: '3'
                config:            
                  severity: warn
    tests:
            - dbt_utils.expression_is_true:
                expression: "TEMPLATENUMBER>0 and TEMPLATENUMBER<200"
                condition: "TEMPLATENUMBER <> NULL"
                config:            
                  severity: warn
                      
    